spring.application.name=WebNongSan
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_WebNongSan;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Hoangmy1703.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect